name: skb.
services:
  backend:
    build: ./crm-backend
    ports:
      - "3000:3000"
    volumes:
      - ./crm-backend:/usr/src/app
    networks:
      - app-network
    environment:
      NODE_ENV: development

networks:
  app-network:
